<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class User
 * @property integer $id
 * @property integer $fid
 * @property string $dataTypes
 * @property string $colors
 * @property string $view
 *
 * @property Facility $facility
 *
 */
class Chart extends ActiveRecord
{

    const VIEW_WEEK = 'week';
    const VIEW_DAY = 'day';
    const VIEW_MONTH = 'month';
    const VIEW_YEAR = 'year';


    public static function tableName()
    {
        return 'chart';
    }

    public function rules()
    {
        return [
            [['id', 'fid'], 'integer'],
            [['fid', 'dataTypes'], 'required'],
            ['view', 'string'],
            [['dataTypes', 'colors'], 'each', 'rule' => ['string']],
            ['view', 'default', 'value' => self::VIEW_WEEK]
        ];
    }

    public function attributeLabels()
    {
        return [];
    }

    public function getFacility()
    {
        return $this->hasOne(Facility::class, ['id' => 'fid']);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if (!empty($this->dataTypes)) {
            $this->dataTypes = unserialize($this->dataTypes);
        }
        if (!empty($this->colors)) {
            $this->colors = unserialize($this->colors);
        }
    }

    public function beforeSave($insert)
    {
        $this->dataTypes = serialize($this->dataTypes);
        $this->colors    = serialize($this->colors);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
